name: TWO Secret Demo Workflow TWO

on: push

jobs:
  secret-demo-job:
    runs-on: ubuntu-latest

    steps:
      - name: Use Secret
        env:
          PASSWORD: ${{ secrets.APP_PASSWORD }}
        run: |
          echo "Using secret password"
          echo "Password length is ${#PASSWORD}"
