name: THREE Secret Demo Workflow FOUR

on: push

jobs:
  secret-demo-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check Secret
        env:
          PASSWORD: ${{ secrets.APP_PASSWORD }}
        run: |
          echo "Checking secret..."
          if [ -z "$PASSWORD" ]; then
            echo "Secret is EMPTY"
          else
            echo "Secret is SET"
            echo "Password length is ${#PASSWORD}"
          fi
