name: THREE Secret Demo Workflow THREE

on: push

jobs:
  n-secret-demo-job-n:
    runs-on: ubuntu-latest

    steps:
      - name: Use Secret THREE
        env:
          PASSWORD: ${{ secrets.APP_PASSWORD }}
        run: |
          echo "THREE Using secret password THREE"
          echo "THREE Password length is ${#PASSWORD}"
